name: Android CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: upgrade rust
        run: rustup toolchain install stable
      - name: add rust target
        run: rustup target add aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android
      - name: flutter pub get
        working-directory: mailway_ui
        run: flutter pub get
      - name: Build with Gradle
        run: sudo ./gradlew build --info --stacktrace

